services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: bank_transactions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bank-transactions:
    build:
      context: ../../
      dockerfile: apps/bank-transactions/Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bank_transactions
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 3001
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
